=== DanaPavlenko/EpamMaven/Epam_Maven/src/main/resources/xml/gemXSD.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="gems" xmlns="gems" elementFormDefault="qualified">

	<xs:element name='gems'>
		<xs:complexType>
			<xs:sequence>
				<xs:element name='gem' type='gemType' minOccurs='0'
					maxOccurs='unbounded' />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="gemType">
		<xs:sequence>
			<xs:element name="name">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="5" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="presiousness">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="precious" />
						<xs:enumeration value="semiprecious" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="origin">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:minLength value="5" />
						<xs:maxLength value="40" />
					</xs:restriction>
				</xs:simpleType>
			</xs:element>

			<xs:element name="visual_parameters">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="color">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="blue" />
									<xs:enumeration value="green" />
									<xs:enumeration value="yellow" />
									<xs:enumeration value="red" />
									<xs:enumeration value="brown" />
									<xs:enumeration value="white" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>
						<xs:element name="transparency">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="0" />
									<xs:maxInclusive value="100" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>

						<xs:element name="edge_number">
							<xs:simpleType>
								<xs:restriction base="xs:integer">
									<xs:minInclusive value="4" />
									<xs:maxInclusive value="15" />
								</xs:restriction>
							</xs:simpleType>
						</xs:element>

					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>

		<xs:attribute name='gemNo' type='xs:integer' />
	</xs:complexType>

	<xs:element name="value">
		<xs:simpleType>
			<xs:restriction base="xs:integer">
				<xs:minInclusive value="1" />
				<xs:maxInclusive value="27" />
			</xs:restriction>
		</xs:simpleType>
	</xs:element>

</xs:schema>

=== DanaPavlenko/EpamMaven/Epam_Maven/target/classes/xml/gemXML.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="gemXSLT.xsl"?>

<gems xmlns="gems"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="gemXSD.xsd">
    <gem gemNo="0">
        <name>emerald</name>
        <preciousness>precious</preciousness>
        <origin>Columbia</origin>
        <visual_parameters>
        <color>green</color>
        <transparency>60</transparency>
        <edge_number>7</edge_number>
        </visual_parameters>
        <value>5</value>
    </gem> 
    
    <gem gemNo="1">
        <name>sapphire</name>
        <preciousness>precious</preciousness>
        <origin>USA</origin>
        <visual_parameters>
        <color>blue</color>
        <transparency>40</transparency>
        <edge_number>5</edge_number>
        </visual_parameters>
        <value>3</value>
    </gem>
    
    <gem gemNo="2">
        <name>ruby</name>
        <preciousness>precious</preciousness>
        <origin>Shri-Lanka</origin>
        <visual_parameters>
        <color>blue</color>
        <transparency>99</transparency>
        <edge_number>12</edge_number>
        </visual_parameters>
        <value>4</value>
    </gem>
            
</gems>
